# Generated by Django 4.0.2 on 2022-05-04 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPreference',
            fields=[
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db.member')),
                ('is_smoking_allowed', models.BooleanField(default=False)),
                ('is_pet_allowed', models.BooleanField(default=False)),
                ('chitchat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.chitchatpreference')),
                ('music_preference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.musicpreference')),
            ],
        ),
    ]
