# Generated by Django 4.0.2 on 2022-05-04 13:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_musicpreference_memberpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_registration_number', models.CharField(max_length=50)),
                ('car_color', models.CharField(max_length=10)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.car')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.member')),
            ],
        ),
    ]
