# Generated by Django 4.0.2 on 2022-04-29 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('driving_license_number', models.CharField(blank=True, max_length=256, null=True)),
                ('driving_license_valid_from', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
