# Generated by Django 4.0.2 on 2022-05-04 13:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('make', models.CharField(max_length=256, null=True)),
                ('model', models.CharField(max_length=256, null=True)),
                ('make_year', models.CharField(max_length=256, null=True)),
                ('comfort_level', models.PositiveSmallIntegerField(max_length=1, null=True)),
            ],
        ),
    ]
