# Generated by Django 4.0.2 on 2022-05-04 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitchatPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
